camel.springboot.main-run-controller: true
spring: 
  profiles: 
    active: stage
    
---

spring: 
  profiles: mock
  activemq:
    brokerUrl: tcp://localhost:61611
    user: admin
    password: admin
    
routeIn: direct:input
routeOut: mock:output

---

spring: 
  profiles: unittest
  
routeIn: activemq:testQueue
routeOut: activemq:foo

---

spring: 
  profiles: dev
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    
routeIn: activemq:testQueue
routeOut: activemq:foo

---

spring: 
  profiles: stage
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    
routeIn: activemq:foo
routeOut: activemq:testQueue

---